### ISSUE TITLE
Functionality of Creating a Todo Task: TodoTask State

### ISSUE THREAD

**Issue by fosa-ij** [fosa-ij/TodoList-EI#16]
Create a todoTask state initially as an empty string and a handleChange updater function to add new todos to the todoTask state using setTodoTask.

Note
The initial state of the todo is an empty string

**Comment by fosa-ij** [comment]
if you need clarity on how to go about it, let me know
we can talk here

**Comment by emmy3oy** [comment]
Yeah. I have an idea of what to do. Let me give it a try first.

**Comment by fosa-ij** [comment]
okay
